# SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Wrapper around NeMo LLM APIs.

NOTE:
    This should be contributed to LangChain to add support for NeMo LLM.
    This is an initial rough version. Needs more improvement.
    Apparently, other teams have been working on this as well. We should sync.

IMPORTANT: This connects to staging right now.
"""
import json
from typing import Any, Dict, List, Optional

import aiohttp
import requests
from langchain.llms.base import LLM
from langchain.utils import get_from_dict_or_env
from pydantic import BaseModel, Extra, root_validator


class NeMoLLM(LLM, BaseModel):
    """Wrapper around NeMoLLM large language models.

    To use, you should have the environment variable ``NeMoLLM_API_KEY``
    set with your API key.

    Example:
        .. code-block:: python

            from langchain.llms import NeMoLLM
            nemo_llm = NeMoLLM(model="gpt530b")
    """

    model: str = "gpt530b"
    """Model name to use."""

    temperature: float = 0.7
    """What sampling temperature to use."""

    tokens_to_generate: int = 50
    """The maximum number of tokens to generate in the completion."""

    top_p: float = 1.0
    """Total probability mass of tokens to consider at each step."""

    nemo_llm_api_key: Optional[str] = None

    stop: Optional[List[str]] = None

    base_url: Optional[str] = None
    """Base url to use, if None decides based on model name."""

    class Config:
        """Configuration for this pydantic object."""

        extra = Extra.forbid

    @root_validator()
    def validate_environment(cls, values: Dict) -> Dict:
        """Validate that api key exists in environment."""
        nemo_llm_api_key = get_from_dict_or_env(
            values, "nemo_llm_api_key", "NEMO_LLM_API_KEY"
        )
        values["nemo_llm_api_key"] = nemo_llm_api_key
        return values

    @property
    def _default_params(self) -> Dict[str, Any]:
        """Get the default parameters for calling NeMoLLM API."""
        return {
            "temperature": self.temperature,
            "tokens_to_generate": self.tokens_to_generate,
            "top_p": self.top_p,
        }

    @property
    def _identifying_params(self) -> Dict[str, Any]:
        """Get the identifying parameters."""
        return {**{"model": self.model}, **self._default_params}

    @property
    def _llm_type(self) -> str:
        """Return type of llm."""
        return "nemo_llm"

    def _call(self, prompt: str, stop: Optional[List[str]] = None) -> str:
        """Call out to NeMoLLM's complete endpoint.

        Args:
            prompt: The prompt to pass into the model.
            stop: Optional list of stop words to use when generating.

        Returns:
            The string generated by the model.

        Example:
            .. code-block:: python

                response = nemo_llm("Tell me a joke.")
        """
        if self.stop is not None and stop is not None:
            raise ValueError("`stop` found in both the input and default params.")
        elif self.stop is not None:
            stop = self.stop
        elif stop is None:
            stop = []
        if self.base_url is not None:
            base_url = self.base_url
        else:
            base_url = "https://stg.llm.ngc.nvidia.com/v1"

        url = f"{base_url}/models/{self.model}/completions"
        response = requests.post(
            url=url,
            headers={
                "Authorization": f"Bearer {self.nemo_llm_api_key}",
                "Content-Type": "application/json",
            },
            json={"prompt": prompt, "stop": stop, **self._default_params},
            timeout=30,
        )
        if response.status_code != 200:
            optional_detail = response.json().get("error")
            raise ValueError(
                f"NeMoLLM /completions call failed with status code {response.status_code}."
                f" Details: {optional_detail}"
            )

        response_json = response.json()
        return response_json["text"]

    async def _acall(self, prompt: str, stop: Optional[List[str]] = None) -> str:
        """Run the LLM on the given prompt and input."""
        async with aiohttp.ClientSession() as session:
            if self.stop is not None and stop is not None:
                raise ValueError("`stop` found in both the input and default params.")
            elif self.stop is not None:
                stop = self.stop
            elif stop is None:
                stop = []
            if self.base_url is not None:
                base_url = self.base_url
            else:
                base_url = "https://stg.llm.ngc.nvidia.com/v1"

            url = f"{base_url}/models/{self.model}/completions"

            async with session.post(
                url,
                headers={
                    "Authorization": f"Bearer {self.nemo_llm_api_key}",
                    "Content-Type": "application/json",
                },
                json={"prompt": prompt, "stop": stop, **self._default_params},
            ) as resp:
                if resp.status != 200:
                    raise Exception(
                        f"Got status code {resp.status} to NeMo LLM engine request."
                    )

                result = json.loads(await resp.text())

                # The stop words do not seem to work correctly, so we compensate
                if stop:
                    for word in stop:
                        if word in result["text"]:
                            result["text"] = result["text"].split(word)[0]

                return result["text"].strip()
