[tox]
envlist = py39, py310, py311

[testenv]
description = Run tests with pytest under different Python versions using Poetry
deps = poetry
skip_install = true
setenv =
    POETRY_VIRTUALENVS_CREATE = false
commands_pre =
    poetry install --no-interaction --no-ansi
commands =
    pytest
