# tox will not do any install.
# uv manages all dependencies and the current package.
# Thus, tests are running against the local files and not the built and installed package.
# How to use:
# do
# > pyenv install 3.10 3.11 3.12
# > pyenv local 3.10 3.11 3.12

[tox]
envlist = py310, py311, py312, py313
runner = uv-venv-lock-runner

[testenv]
description = Run tests with pytest under different Python versions
extras = all
dependency_groups = dev
commands =
    pytest tests/ --import-mode importlib

[pytest]
asyncio_default_fixture_loop_scope = function
