# Simple example of how to use actions.

flows:
  - elements:
    - user: ask math question
    - execute: wolfram alpha request
    - bot: respond to math question
    - bot: ask if user happy

  - elements:
    - user: ask conversion question
    - execute: wolfram alpha request
    - bot: respond to math question
    - bot: ask if user happy

  - elements:
      - user: ask conversion question
      - execute: wolfram alpha request
      - bot: respond to math question
      - bot: ask if user happy

# Using OpenAI
models:
  - type: main
    engine: openai
    model: text-davinci-003
