from typing import Any, List, Mapping, Optional

from langchain.llms.base import LLM
from pydantic import BaseModel

from colangflows.rails import LLMRails, RailsConfig


class FakeLLM(LLM, BaseModel):
    """Fake LLM wrapper for testing purposes."""

    responses: List
    i: int = 0

    @property
    def _llm_type(self) -> str:
        """Return type of llm."""
        return "fake-list"

    def _call(self, prompt: str, stop: Optional[List[str]] = None) -> str:
        """First try to lookup in queries, else return 'foo' or 'bar'."""
        response = self.responses[self.i]
        self.i += 1
        return response

    async def _acall(self, prompt: str, stop: Optional[List[str]] = None) -> str:
        """First try to lookup in queries, else return 'foo' or 'bar'."""
        response = self.responses[self.i]
        self.i += 1
        return response

    @property
    def _identifying_params(self) -> Mapping[str, Any]:
        return {}


class TestChat:
    """Helper class for easily writing tests.

    Usage:
        config = RailsConfig.from_path(...)
        chat = TestChat(
            config,
            llm_completions=[
                "Hello! How can I help you today?",
            ],
        )

        chat.user("Hello! How are you?")
        chat.bot("Hello! How can I help you today?")

    """

    # Tell pytest that this class is not meant to hold tests.
    __test__ = False

    def __init__(self, config: RailsConfig, llm_completions: List[str]):
        """Creates a TestChat instance.

        :param config: The rails configuration that should be used.
        :param llm_completions: The completions that should be generated by the fake LLM.
        """
        self.llm = FakeLLM(responses=llm_completions)
        self.config = config
        self.app = LLMRails(config, llm=self.llm)
        self.history = []

    def user(self, msg: str):
        self.history.append({"role": "user", "content": msg})

    def bot(self, msg: str):
        result = self.app.generate(messages=self.history)
        assert result, "Did not receive any result"
        assert (
            result["content"] == msg
        ), f"Expected `{msg}` and received `{result['content']}`"
        self.history.append(result)

    def __rshift__(self, msg: str):
        self.user(msg)

    def __lshift__(self, msg: str):
        self.bot(msg)
