name: Build and Test Python Wheel

on:
  push:
    tags:
      - "v*"

env:
  POETRY_VERSION: "1.8.2"
  PYTHON_VERSION: "3.11"

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Extract Version Tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Install Poetry ${{ env.POETRY_VERSION }}
        uses: abatilo/actions-poetry@v2

      - name: Set execute permissions for build script
        run: chmod +x ./.github/scripts/build.sh

      - name: Build Wheel
        run: |
          ./.github/scripts/build.sh
          echo "WHEEL_FILE=$(ls dist/*.whl)" >> $GITHUB_ENV

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nemoguardrails-${{ env.VERSION }}.whl
          path: dist/nemoguardrails-${{ env.VERSION }}-py3-none-any.whl
