name: PR Tests
env:
  PYTHON_VERSION: 3.11

on:
  pull_request:
    paths-ignore:
      - "**/*.md"

jobs:
  call-tests:
    uses: ./.github/workflows/_test.yml
    with:
      os: ubuntu-latest
      python-version: "3.10"
